apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: the-project-step-3
  name: the-project-step-3
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: the-project-step-3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: the-project-step-3
    spec:
      containers:
        - image: papastepanhdi/devops-with-kubernetes:1.5
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          imagePullPolicy: IfNotPresent
          name: devops-with-kubernetes
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30